# Generated by Django 3.0.1 on 2020-08-30 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('sub_categ', models.CharField(blank=True, choices=[('Airpods', 'Airpods'), ('Bathtub', 'Bathtub'), ('Bed', 'Bed'), ('Bedsheet', 'Bedsheet'), ('Belt', 'Belt'), ('Book', 'Book'), ('Bracelet', 'Bracelet'), ('Camera', 'Camera'), ('Carpet', 'Carpet'), ('Chair', 'Chair'), ('Charger', 'Charger'), ('Coat', 'Coat'), ('Colors', 'Colors'), ('Comod', 'Comod'), ('Copy', 'Copy'), ('Cupboard', 'Cupboard'), ('Curtain', 'Curtain'), ('Handbag', 'Handbag'), ('Headphones', 'Headphones'), ('Jacket', 'Jacket'), ('Laptop', 'Laptop'), ('Mike', 'Mike'), ('Necklace', 'Necklace'), ('Pant', 'Pant'), ('PC', 'PC'), ('Pen & Pencil', 'Pen & Pencil'), ('Pillow', 'Pillow'), ('Purse', 'Purse'), ('Ring', 'Ring'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Slippers', 'Slippers'), ('Soap & Shampoo', 'Soap & Shampoo'), ('Socks', 'Socks'), ('Sofa', 'Sofa'), ('Table', 'Table'), ('Toilet Paper', 'Toilet Paper'), ('Toothbrush & paste', 'Toothbrush & paste'), ('T-Shirt', 'T-Shirt'), ('TV', 'TV'), ('VideoProjector', 'VideoProjector'), ('Watch', 'Watch'), ('Others', 'Others')], max_length=200, null=True)),
                ('brands', models.CharField(blank=True, choices=[('Acer', 'Acer'), ('Adidas', 'Adidas'), ('Apple', 'Apple'), ('Canon', 'Canon'), ('Champion', 'Champion'), ('Colors', 'Colors'), ('Dell', 'Dell'), ('Fila', 'Fila'), ('Goldstar', 'Goldstar'), ('Gucci', 'Gucci'), ('Hp', 'Hp'), ('Hubolt', 'Hubolt'), ('Huwawei', 'Huwawei'), ('IMac', 'IMac'), ('Jordan', 'Jordan'), ('Lava', 'Lava'), ('LG', 'LG'), ('Louis Vitton', 'Louis Vitton'), ('Macbook', 'Macbook'), ('Motorola', 'Motorola'), ('Nike', 'Nike'), ('Nikon', 'Nikon'), ('Nokia', 'Nokia'), ('One Plus', 'One Plus'), ('Oppo', 'Oppo'), ('Razor', 'Razor'), ('Realme', 'Realme'), ('Rolex', 'Rolex'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Underarmour', 'Underarmour'), ('Versace', 'Versace'), ('Videocon', 'Videocon'), ('Vivo', 'Vivo'), ('Xaomi', 'Xaomi'), ('Others', 'Others')], max_length=200, null=True)),
                ('material', models.CharField(blank=True, choices=[('Wollen', 'Wollen'), ('Cotton', 'Cotton'), ('Polyster', 'Polyster'), ('Others', 'Others')], max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children')], max_length=10, null=True)),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Gold', 'Gold'), ('Green', 'Green'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow'), ('Others', 'Others')], default=None, max_length=10, null=True)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('Others', 'Others')], default=None, max_length=10, null=True)),
                ('price', models.IntegerField(default='')),
                ('discount_percent', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(default='', max_length=200)),
                ('image1', models.ImageField(blank=True, default='', null=True, upload_to='eapp/images')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='eapp/images')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='eapp/images')),
                ('seller', models.CharField(blank=True, default='Respective Company', max_length=200)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Wise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Accessories', 'Accessories'), ('Bathroom Items', 'Bathroom Items'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Household Items', 'Household Items'), ('Mobile Phones', 'Mobile Phones'), ('Stationery Items', 'Stationery Items'), ('Others', 'Others')], max_length=120)),
                ('imagesc1', models.ImageField(default='', upload_to='eapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('Airpods', 'Airpods'), ('Bathtub', 'Bathtub'), ('Bed', 'Bed'), ('Bedsheet', 'Bedsheet'), ('Belt', 'Belt'), ('Book', 'Book'), ('Bracelet', 'Bracelet'), ('Camera', 'Camera'), ('Carpet', 'Carpet'), ('Chair', 'Chair'), ('Charger', 'Charger'), ('Coat', 'Coat'), ('Colors', 'Colors'), ('Comod', 'Comod'), ('Copy', 'Copy'), ('Cupboard', 'Cupboard'), ('Curtain', 'Curtain'), ('Handbag', 'Handbag'), ('Headphones', 'Headphones'), ('Jacket', 'Jacket'), ('Laptop', 'Laptop'), ('Mike', 'Mike'), ('Necklace', 'Necklace'), ('Pant', 'Pant'), ('PC', 'PC'), ('Pen & Pencil', 'Pen & Pencil'), ('Pillow', 'Pillow'), ('Purse', 'Purse'), ('Ring', 'Ring'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Slippers', 'Slippers'), ('Soap & Shampoo', 'Soap & Shampoo'), ('Socks', 'Socks'), ('Sofa', 'Sofa'), ('Table', 'Table'), ('Toilet Paper', 'Toilet Paper'), ('Toothbrush & paste', 'Toothbrush & paste'), ('T-Shirt', 'T-Shirt'), ('TV', 'TV'), ('VideoProjector', 'VideoProjector'), ('Watch', 'Watch'), ('Others', 'Others')], max_length=200)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Type_Wise')),
            ],
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', null=True)),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Type_Wise'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('latest', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=150)),
                ('phonenumber', models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('items', models.ManyToManyField(to='eapp.OrderItems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.BooleanField(default=False)),
                ('final_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.OrderItems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_comment', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
